name: Merge to develop

on:
  push:
    branches: [ develop ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    - name: version
      id: generate_version
      run: echo "::set-output name=version::1.26.$(($GITHUB_RUN_NUMBER))"
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: Publish Win-x64
      run: dotnet publish Topo/Topo.csproj -c Release -p:PublishProfile=FolderProfile -o ../output/win-x64 -p:Version=${{ steps.generate_version.outputs.version }} -p:FileVersion=${{ steps.generate_version.outputs.version }}
    - name: Publish Osx-x64
      run: dotnet publish Topo/Topo.csproj -c Release -p:PublishProfile=FolderProfileOsx -o ../output/osx-x64 -p:Version=${{ steps.generate_version.outputs.version }} -p:FileVersion=${{ steps.generate_version.outputs.version }}    
    - name: Archive Win-x64 Publish Folder
      uses: thedoctor0/zip-release@master
      with:
        type: zip
        filename: '/home/runner/work/Topo/topo-win.zip'
        directory: /home/runner/work/Topo/output/win-x64/
    - name: Archive Osx-x64 Publish Folder
      uses: thedoctor0/zip-release@master
      with:
        type: zip
        filename: '/home/runner/work/Topo/topo-osx.zip'
        directory: /home/runner/work/Topo/output/osx-x64/
    - name: Create Release
      uses: actions/create-release@v1
      id: create_release
      with:
        draft: true
        prerelease: false
        release_name: v${{ steps.generate_version.outputs.version }}
        tag_name: v${{ steps.generate_version.outputs.version }}
      env:
        GITHUB_TOKEN: ${{ github.token }}
    - name: Upload Win-x64 to Release
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ github.token }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: '/home/runner/work/Topo/topo-win.zip'
        asset_name: topo-win.zip
        asset_content_type: application/zip        
    - name: Upload Osx-x64 to Release
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ github.token }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: '/home/runner/work/Topo/topo-osx.zip'
        asset_name: topo-osx.zip
        asset_content_type: application/zip        
